POST http://192.168.1.102:8081/create-event
Content-Type: application/json

{
  "name": "Know Your Campus",
  "description": "Answer some questions\nabout the campus!",
  "startTime": "2024-10-25T12:16+13:00"
}
